### ISSUE TITLE
Invisible butterflies on servers

### ISSUE THREAD

**Issue by mxnmnm** [doc-bok/Butterflies#103]
I need to do more testing but it seems that butterflies end up being invisible on servers but not singleplayer. I'm not sure if this is a mod interaction or not so I'll test it out but if you have any ideas of what might be causing this a fix would be great. Otherwise I'll come back here and tell you what issues/info I find. Figured I should let you know this does seem to be a problem.

**Comment by mxnmnm** [comment]
This is not an issue with any other mods as it occurs with only this mod installed. So I hope you can find a fix.

**Comment by mxnmnm** [comment]
This seems to have been an issue first introduced in version 2.1.1

**Comment by mxnmnm** [comment]
Oh yea it does it for all mobs

**Comment by mxnmnm** [comment]
Will there be another way to fix the caterpillar issue?

**Comment by doc-bok** [comment]
I'm not sure. I'm trying to reproduce this one locally to see if I can understand what's going on and develop a better fix.

**Comment by doc-bok** [comment]
Okay, I have managed to reproduce it and I think I know what the problem is. I had a fundamental misunderstanding of how things work :/

I should be able to fix this properly today. Just need to come up with a good solution.

**Comment by mxnmnm** [comment]
Yay gl finding a fix :)

**Comment by doc-bok** [comment]
Well that one was a doozy, but on the plus side I learned a lot about how networking works in Minecraft. It's fixed now, but I want to take a look at your other bug before I do another release. If I can fix it quickly then it's worth including both fixes.
