### ISSUE TITLE
Butterflies Not Appearing When Spawned

### ISSUE THREAD

**Issue by HamberAlert** [doc-bok/Butterflies#108]
As said in the title, butterflies aren't showing up when spawned nor are the eggs, chrysalises and caterpillars. Currently playing on 1.20.1 with a personally made modpack. I've turned off my shaders and resource packs and they still aren't showing up.

**Comment by doc-bok** [comment]
I can't reproduce this one locally :(

Can you confirm you're using the latest version of the mod (3.0.2)? Also are you running just a client, or are you connecting to a server? A list of mods might help as well - it could be a bad mod interaction.

**Comment by doc-bok** [comment]
Closing this as cannot reproduce.
