### ISSUE TITLE
Bottled Butterflies makes my server crash?

### ISSUE THREAD

**Issue by EclipsedLB** [doc-bok/Butterflies#125]
So, I have recently opened my modded server which included this mod. After someone placed down a Bottled Butterfly and broke it, the server completely crashed and shut down. I know the Bottled Butterfly is the cause since it says it in the latest crash report. Any Ideas if I can fix it on my own? Otherwise, bug report.

Here is the crash down below:

[crash-2024-03-18_17.39.47-server.txt](https://github.com/doc-bok/Butterflies/files/14644829/crash-2024-03-18_17.39.47-server.txt)

**Comment by doc-bok** [comment]
Thanks for the report. After some quick research it seems that Forge only incudes `apache.commons` in the client for some reason, which is why the server is crashing. I'm going to have to fix it and create an update unfortunately.

**Comment by doc-bok** [comment]
Okay, it was a one line fix so I've created a new release that should fix this crash. It should be available everywhere, but it's still pending approval on CurseForge.

**Comment by EclipsedLB** [comment]
Alright thank you!
