### ISSUE TITLE
Crash on multiplayer server

### ISSUE THREAD

**Issue by katubug** [doc-bok/Butterflies#54]
Hi! I'm using version 2.0 of the mod, but unfortunately my server won't start up when the mod is on it.

[crash-2023-12-17_12.24.33-fml.txt](https://github.com/doc-bok/Butterflies/files/13697156/crash-2023-12-17_12.24.33-fml.txt)

**Comment by doc-bok** [comment]
Thanks for reporting! 

Looks like it's loading some GUI files which don't exist on the server. Should hopefully be easy to reproduce.

**Comment by doc-bok** [comment]
The latest version should fix the crash: https://github.com/doc-bok/Butterflies/releases/tag/2.0.1

Enjoy and feel free to report any other problems you may find.
