### ISSUE TITLE
Butterfly Eggs in Azalea Leaves are a broken texture

### ISSUE THREAD

**Issue by dandy-is-lion** [doc-bok/Butterflies#56]
Minecraft: 1.20.1
Forge: 47.2.0
Mod Version: 2.0.1

All Butterfly Eggs applied to Azalea Leaves result in a broken/missing texture until they hatch. No other mods or texture packs installed. Also are there any plans to support leaves and biomes for spawning from other mods like [Biomes O' Plenty](https://modrinth.com/mod/biomes-o-plenty), [Chipped](https://modrinth.com/mod/chipped), and [Nature's Aura](https://modrinth.com/mod/natures-aura)?

Steps to reproduce:
- Choose any Butterfly Egg
- Apply it to non-flowering Azalea Leaves

![2023-12-25_14 14 33](https://github.com/doc-bok/Butterflies/assets/125793933/979d9705-e84a-49d2-97c7-307b7ffc803d)

**Comment by doc-bok** [comment]
Thanks for the report. Looks like it's just a missing model/texture so should be an easy fix. I'll look at it after new year when I get back home.

I do plan to support other biome modes. I'm looking at making it more data driven in the next version which should make it easier to support custom Biomes. 

At the moment you could do it by adding your own biome modifiers. That would allow butterflies to spawn, but supporting custom leaves will need changes to the code at the moment.

**Comment by dandy-is-lion** [comment]
Sweet! I'll look forward to it. Happy New Year!
How would I go about adding my own biome modifiers? Is that only editable within the code or is that part of a config?

**Comment by doc-bok** [comment]
> Sweet! I'll look forward to it. Happy New Year!
> How would I go about adding my own biome modifiers? Is that only editable within the code or is that part of a config?

There's a tutorial on them here:

https://forge.gemwire.uk/wiki/Biome_Modifiers

I'm not 100% sure if this would work in a data pack, but I'd be interested in finding out.

**Comment by doc-bok** [comment]
I made a new release today that should fix this, as well as some other minor issues.

**Comment by dandy-is-lion** [comment]
Thanks! Just got the modrinth update notification. Been wanting to make a butterfly shelter to go with my apiary. Can't wait to figure out the secret achievement :eyes:
