### ISSUE TITLE
Crossmod Support

### ISSUE THREAD

**Issue by doc-bok** [doc-bok/Butterflies#66]
Allow butterflies to spawn in custom biomes. Currently requested:

- Biomes O' Plenty
- Chipped
- Nature's Aura
- Regions Unexplored,
- Ars Noveau
- Ars elemental,
- Terralith

**Comment by mxnmnm** [comment]
regions unexplored, ars noveau, ars elemental, and terralith pls or just use biome tags so you don't have to manually add biomes

**Comment by doc-bok** [comment]
If you know how to create biome modifiers then you may be able to do this yourself already. These are the biome modifiers used by the mod for vanilla biomes:

https://github.com/doc-bok/Butterflies/tree/main/src/main/resources/data/butterflies/forge/biome_modifier

I'm not sure if you can add these to a data pack, but it might work.

**Comment by doc-bok** [comment]
The new biome modifiers use tags, so the next version should be compatible with any mods that also use these tags.
