### ISSUE TITLE
Suggestion: pollenation and spreading of flowers

### ISSUE THREAD

**Issue by GreenForzeGaming** [doc-bok/Butterflies#77]
an absolute great addition would be for butterflies to spread flowers during their life spawn and have some species prefer specific flowers more than others for faster spread. ive always wanted a cool flower spread function

**Comment by doc-bok** [comment]
Thanks for the suggestion! 

I have considered a mechanic like this, but I'm not 100% sure how to make it work yet. I'm thinking something along the lines of pollenating flowers and having new flowers grow near them. That way it would be possible to make a semi-automated flower farm, while still requiring some resource gathering and butterfly catching to get started.

The per-species preference is a really nice idea I hadn't thought of. Adds a new mechanism where different butterflies would be better for certain flower types. Also gives a reason for flower farmers to pursue certain species of butterfly.
