### ISSUE TITLE
Modded Leaf Support?

### ISSUE THREAD

**Issue by mxnmnm** [doc-bok/Butterflies#95]
I'm using regions unexplored and you can't put butterfly eggs in leaves from that mod :(

**Comment by doc-bok** [comment]
Now that butterfly eggs are entities, they should work with leaf blocks from any mod.

**Comment by mxnmnm** [comment]
Are they entities in the latest version??? Or is this something that hasn't been released yet?

**Comment by doc-bok** [comment]
No, these will be released in the next version.
