### ISSUE TITLE
Invisible Caterpillars

### ISSUE THREAD

**Issue by mxnmnm** [doc-bok/Butterflies#96]
Caterpillars go in and out of existence for me. I am using a lot of mods that tweak rendering and such so one of those is probably involved. If you need me to diagnose what the conflict is I can do that but if you have an idea of how to fix this otherwise pls do that.

**Comment by doc-bok** [comment]
This is likely down to a bad optimisation in one of those mods. I noticed this with 1.19 and had to expand the bounding box for rendering manually so the caterpillars wouldn't disappear. I may pull that change into the 1.20 version as well to see if that fixes it, but I'm not 100% sure that it will work.

**Comment by doc-bok** [comment]
I've created a test release here:

**Comment by doc-bok** [comment]
I've created a test release here:

https://github.com/doc-bok/Butterflies/releases/tag/2.1.1a

If you want to try it and see if it fixes the caterpillar issue, that would be greatly appreciated. Although this should be a safe change, I'd still recommend backing up your world, or trying it in a test world, just in case.

If this doesn't work, I'd love a list of mods that you're using. It should help me track down the cause of the bug so I can fix it for you.

**Comment by mxnmnm** [comment]
Fixed! :D

**Comment by doc-bok** [comment]
Awesome :)

**Comment by mxnmnm** [comment]
![2024-02-06_22 45 46](https://github.com/doc-bok/Butterflies/assets/8508976/2756295f-6dcd-4ac8-b9c6-39896f07caab)
it's beautiful (pehuki is fun lol)

**Comment by doc-bok** [comment]
Haha, was not expecting to see giant caterpillars like this!
